### ISSUE TITLE
Heading rendering problems  in markdown

### ISSUE THREAD

**Issue by Creedowl** [queensferryme/hugo-theme-texify#2]
I found a heading rendering problem in rendering markdown file using hugo that confused me. Hugo will render heading in markdown like this: 
`# some heading` -> `<h1 id="some_heading">some heading</h1>` 
It's content becomes it's id and so are the other heading tags (h1-h6). 
This may cause rendering confusion if I have a style with the same name to a heading content. eg. 
`# header` -> `<h1 id="header">header</h1>`

**Comment by queensferryme** [comment]
This issue won't be fixed currently with the reasons listed as follows:
- Currently we only have four built-in IDs: `wrapper`, `header`, `main` and `footer`. Chances that these words are used as a heading is very low.
- There is a compatibility problem with **hugo** since the default markdown renderer changed from `blackfriday` to `goldmark` since v0.60 if I am not mistaken. The two renderers' approaches to handle auto heading IDs are different.

We shall come back to this issue if it arises in some scenarios in the future.
