### ISSUE TITLE
How do I add a favicon?

### ISSUE THREAD

**Issue by Abdulee** [queensferryme/hugo-theme-texify#4]
Hello,
I have a favicon placed for my site in /static/img/favicon.ico it is a 64x64 file. I have added favicon=/img/favicon.ico in config.toml however it is not working...
Any help on how I can do this?

**Comment by queensferryme** [comment]
Thanks for reporting the issue. Adding a favicon to your site is not supported currently, I will add this feature in a few days.

**Comment by queensferryme** [comment]
@Abdulee Hey, sorry for the delay. In case you are still interested, I think putting your `favicon.ico` at `static/favicon.ico` would solve your problem.

**Comment by queensferryme** [comment]
I have come up with a fiix in 7115035. In order to customize favicon, you will need to add something like these in your `config.toml`:
```toml
[params]
  # ...
  favicon = "/favicon.ico"
```
- If you put your `favicon.ico` at `static/favicon.ico`, use `"/favicon.ico"`;
- If you put your `favicon.ico` at `static/img/favicon.ico`, use `"/img/favicon.ico"`;
- you can even link to any valid icon on the Internet with its url, for example using GitHub's favicon `"https://github.githubassets.com/favicons/favicon.svg"`

Let me know if you need more help!

**Comment by Abdulee** [comment]
Great! I was able to use favicon already with by putting it in /static/ but this should make stuff even better. Great theme and good work :)
